export interface MergeBody {
    main_cid: string;
    other_cid: string;
    c_eMailAddress: string;
    c_carRegNo: string | null;
    c_nationality_id: string;
    c_occupationBranch: string | null;
    c_postBox: string | null;
    c_birthCity: string | null;
    bookingGuestCharacteristicsLST: string;
    c_company: string;
    c_title: string;
    c_occupation: string | null;
    c_salutation_id: string;
    c_documentType_id: string;
    c_lastName: string;
    c_companyRegNo: string | null;
    c_firstName: string;
    c_region: string | null;
    c_addressLine1: string;
    c_comment: string | null;
    c_postCode: string;
    c_addressLine1Plus: string | null;
    c_cityPlus: string | null;
    c_city: string;
    c_birthDay: string | null;
    c_faxNo: string | null;
    c_country_id: string;
    c_taxNo: string;
    c_phoneNo: string;
    c_documentNo: string | null;
    c_webUrl: string | null;
    c_noOfStays: string | null;
}
