export type FeatureInputType = 'checkbox' | 'number' | 'string';
export type FeatureColumn = { key: string, label: string, type: FeatureInputType } | { divider: true };

export const bedFeatures = [
    { key: 'app_singleBeds', label: 'ETD_countSingleBeds', type: 'number' },
    { key: 'app_doubleBeds', label: 'ETD_countDoubleBeds', type: 'number' },
    { key: 'frenchBed', label: 'ETD_frenchBed', type: 'number' },
    { key: 'kingSizeBed', label: 'ETD_kingSizeBed', type: 'number' },
    { key: 'etagenBett', label: 'ETD_BunkBeds', type: 'number' },
    { key: 'babyBed', label: 'ETD_ExtraBabyBedPossible', type: 'number' },
    { key: 'schlafCouch1Pers', label: 'ETD_SleepingCouch1Pers', type: 'number' },
    { key: 'schlafCouch2Pers', label: 'ETD_SleepingCouch2Pers', type: 'number' },
];


export default [
    [
        // [WARN] all values ​​in the key property must be unique in all lists
        { key: 'balcony', label: 'ETD_Balcony', type: 'checkbox' },
        { key: 'terasse', label: 'ETD_Terrace', type: 'checkbox' },
        { key: 'garage', label: 'ETD_Garage', type: 'checkbox' },
        { key: 'eigenerEingang', label: 'ETD_OwnEntrance', type: 'checkbox' },
        { divider: true },
        { key: 'towls', label: 'ETD_Towls', type: 'checkbox' },
        { key: 'hairDryer', label: 'ETD_Hairdryer', type: 'checkbox' },
        { key: 'bathrobe', label: 'ETD_Bathrobe', type: 'checkbox' },
        { key: 'std_bathShower', label: 'ETD_BathShower', type: 'checkbox' },
        { key: 'bad', label: 'ETD_Bath', type: 'checkbox' },
        { key: 'dusche', label: 'ETD_Shower', type: 'checkbox' },
        { key: 'whirlpoolBad', label: 'ETD_Jacuzzi', type: 'checkbox' },
        { key: 'doubleSink', label: 'ETD_doubleSink', type: 'checkbox' },
        { key: 'wc', label: 'ETD_WC', type: 'checkbox' },
        { key: 'wcGetrennt', label: 'ETD_SplitWC', type: 'checkbox' },
        { key: 'bidet', label: 'ETD_Bidet', type: 'checkbox' },
        { key: 'schwimmbad', label: 'ETD_SwimmingPool', type: 'checkbox' },
        { key: 'sauna', label: 'ETD_Sauna', type: 'checkbox' },
        { key: 'std_isolabella', label: 'ETD_Isolabella', type: 'checkbox' },
        { key: 'waschMaschine', label: 'ETD_WashingMachine', type: 'checkbox' },
    ],
    [
        { key: 'sitzEcke', label: 'ETD_CornerUnit', type: 'checkbox' },
        { key: 'schreibTisch', label: 'ETD_WritingTable', type: 'checkbox' },
        { key: 'safe', label: 'ETD_Safe', type: 'checkbox' },
        { key: 'miniBar', label: 'ETD_MiniBar', type: 'checkbox' },
        { divider: true },
        { key: 'breadrollService', label: 'ETD_BreadrollService', type: 'checkbox' },
        { key: 'seperateKitchen', label: 'ETD_SeperateKitchen', type: 'checkbox' },
        { key: 'wohnKuche', label: 'ETD_EatInKitchen', type: 'checkbox' },
        { key: 'cookingFacility', label: 'ETD_CookingFacility', type: 'checkbox' },
        { key: 'geschirrspulMaschine', label: 'ETD_Dishwasher', type: 'checkbox' },
        { key: 'cutlery', label: 'ETD_Cutlery', type: 'checkbox' },
        { key: 'kaffeeMaschine', label: 'ETD_CoffeeMachine', type: 'checkbox' },
        { key: 'kaffeeAutomat', label: 'ETD_CoffeeVending', type: 'checkbox' },
        { key: 'wasserKocher', label: 'ETD_Kettle', type: 'checkbox' },
        { key: 'microwelle', label: 'ETD_Microwave', type: 'checkbox' },
        { key: 'fridge', label: 'ETD_fridge', type: 'checkbox' },
        { key: 'bakingOven', label: 'ETD_bakingOven', type: 'checkbox' },
        { key: 'backRohr', label: 'ETD_oven', type: 'checkbox' },
        { key: 'cooker2Plate', label: 'ETD_Cooker2Plate', type: 'checkbox' },
        { key: 'cooker4Plate', label: 'ETD_Cooker4Plate', type: 'checkbox' },
    ],
    [
        { key: 'antiAllergie', label: 'ETD_AntiAllergy', type: 'checkbox' },
        { key: 'nichtRaucher', label: 'ETD_NonSmoking', type: 'checkbox' },
        { key: 'behinderteGerecht', label: 'ETD_DisabledEquipped', type: 'checkbox' },
        { divider: true },
        { key: 'telephone', label: 'ETD_Telephone', type: 'checkbox' },
        { key: 'radio', label: 'ETD_Radio', type: 'checkbox' },
        { key: 'std_cable_sat', label: 'ETD_CableSat', type: 'checkbox' },
        { key: 'internet', label: 'ETD_Internet', type: 'checkbox' },
        { key: 'klima', label: 'ETD_AC', type: 'checkbox' },
        { divider: true },
        { key: 'std_bedding', label: 'ETD_Bedding', type: 'checkbox' },
        { key: 'singleBed', label: 'ETD_ExtraSingleBedPossible', type: 'checkbox' },
        { key: 'wohnzimmerMitSchlafcouch', label: 'ETD_LivingRoomWithSleepCouch', type: 'checkbox' },
        { key: 'wohnSchlafZimmerGetrennt', label: 'ETD_SeperateLivingSleepingRooms', type: 'checkbox' },
        { key: 'seperateLivingRoom', label: 'ETD_SeperateLivingRoom', type: 'checkbox' },
        { key: 'kinderZimmer', label: 'ETD_Nursery', type: 'checkbox' },
        { divider: true },
        { key: 'pitch', label: 'ETD_Pitch', type: 'checkbox' },
        { key: 'pitchSquareMeters', label: 'ETD_SquareMeters', type: 'string' },
        { key: 'water', label: 'ETD_water', type: 'checkbox' },
        { key: 'sewage', label: 'ETD_sewage', type: 'checkbox' },
        { key: 'electricity', label: 'ETD_electricity', type: 'checkbox' },
        { key: 'electricityAmpereValue', label: 'ETD_ampere', type: 'string' },
    ],
    [
        { key: 'roomSizeM2', label: 'ETD_SquareMeters', type: 'string' },
        { key: 'anzahlSchlafzimmer', label: 'ETD_countSleepingRooms', type: 'number' },
        { key: 'std_bathRoom', label: 'ETD_countBathRooms', type: 'number' },
        { divider: true },
        ...bedFeatures
    ]
] as FeatureColumn[][];
